# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
    # specify the version you desire here
    - image: cimg/node:18.4.0

    working_directory: ~/repo

    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout

      - run:
          name: Install dependencies
          working_directory: ~/repo
          command: |
            npm i
            npm i --legacy-peer-deps mhy@13.2.0 -g

      - deploy:
          name: Trigger deployment
          working_directory: ~/repo
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
            sh ./ci.sh
